import { StyleSheet } from 'react-native';
import { spacing } from '@/theme/spacing';
import { ColorTheme } from '@/theme/colors';
import { radius } from '@/theme/radius';
import { getGlassStyle } from '@/styles/common';

export const createStyles = (theme: ColorTheme) => StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: theme.background.default,
    },
    background: {
        flex: 1,
    },
    safeArea: {
        flex: 1,
    },
    header: {
        paddingHorizontal: spacing.l,
        paddingTop: spacing.xl,
        paddingBottom: spacing.m,
    },
    headerTitle: {
        fontSize: 28,
        fontWeight: '800',
        color: theme.text.primary,
    },
    headerSubtitle: {
        fontSize: 16,
        color: theme.text.secondary,
        marginTop: 4,
    },
    scrollContent: {
        paddingBottom: spacing.xxl,
    },
    searchSection: {
        marginHorizontal: spacing.l,
        marginTop: spacing.m,
        padding: spacing.l,
        ...getGlassStyle(theme),
        backgroundColor: theme.mode === 'dark' ? 'rgba(30, 41, 59, 0.3)' : 'rgba(255, 255, 255, 0.5)',
        borderRadius: radius.xl,
    },
    searchTitleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: spacing.l,
        gap: spacing.s,
    },
    searchTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: theme.text.primary,
    },
    // Extracted
    headerTopRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    qrButton: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: theme.background.card,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: theme.palette.primary[500],
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    grid: {
        gap: spacing.m,
    },
    row: {
        flexDirection: 'row',
        gap: spacing.m,
    },
    halfField: {
        flex: 1,
    },
    verificationBadgeContainer: {
        position: 'absolute',
        right: spacing.m,
        top: '50%',
        marginTop: -10,
        zIndex: 10,
    },
    verificationBadge: {
        width: 20,
        height: 20,
        borderRadius: 10,
        backgroundColor: theme.palette.primary[500],
        justifyContent: 'center',
        alignItems: 'center',
    },
    searchButton: {
        marginTop: spacing.m,
        borderRadius: radius.l,
        height: 56,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: spacing.s,
        overflow: 'hidden',
        shadowColor: theme.palette.primary[500],
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: theme.mode === 'dark' ? 0.4 : 0.25,
        shadowRadius: 12,
        elevation: 8,
    },
    searchButtonGradient: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        borderRadius: radius.l,
    },
    searchButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '700',
        letterSpacing: 0.5,
    },
    clearButton: {
        marginLeft: 'auto',
        paddingHorizontal: spacing.m,
        paddingVertical: spacing.s,
        borderRadius: radius.m,
        backgroundColor: theme.mode === 'dark' ? theme.palette.primary[900] : theme.palette.primary[50],
    },
    clearButtonText: {
        fontWeight: '700',
    },
    fieldWrapper: {
        marginTop: spacing.m,
    },
    statusSection: {
        marginTop: spacing.s,
    },
    resultsSection: {
        marginTop: spacing.xl,
        paddingHorizontal: spacing.l,
    },
    resultsHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: spacing.l,
        position: 'relative',
        zIndex: 50, // Elevates the entire header (and dropdown child) above the cards
    },
    resultsTitle: {
        fontSize: 22,
        fontWeight: '800',
        color: theme.text.primary,
        letterSpacing: 0.3,
    },
    resultsCount: {
        backgroundColor: theme.mode === 'dark' ? theme.palette.primary[900] : theme.palette.primary[50],
        paddingHorizontal: 14,
        paddingVertical: 6,
        borderRadius: radius.full,
        borderWidth: 1,
        borderColor: theme.mode === 'dark' ? theme.palette.primary[800] : theme.palette.primary[100],
    },
    resultsCountText: {
        fontSize: 15,
        fontWeight: '800',
        color: theme.palette.primary[500],
        letterSpacing: 0.5,
    },
    resultCard: {
        marginBottom: spacing.l,
        borderRadius: radius.l,
        overflow: 'hidden',
        ...getGlassStyle(theme),
        backgroundColor: theme.mode === 'dark' ? 'rgba(30, 41, 59, 0.3)' : 'rgba(255, 255, 255, 0.5)',
        shadowColor: theme.palette.primary[500],
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: theme.mode === 'dark' ? 0.2 : 0.05,
        shadowRadius: 16,
    },
    cardContent: {
        padding: spacing.l,
    },
    cardHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    cardHeaderLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: spacing.m,
        flex: 1,
    },
    cardHeaderRight: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
    },
    avatarContainer: {
        width: 52,
        height: 52,
        borderRadius: 26,
        backgroundColor: theme.mode === 'dark' ? theme.palette.primary[900] : theme.palette.primary[50],
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 2,
        borderColor: theme.mode === 'dark' ? theme.palette.primary[800] : theme.palette.primary[100],
        shadowColor: theme.palette.primary[500],
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
    },
    patientInfo: {
        flex: 1,
    },
    patientName: {
        fontSize: 17,
        fontWeight: '700',
        color: theme.text.primary,
        letterSpacing: 0.2,
    },
    patientId: {
        marginTop: 2,
        fontSize: 12,
        color: theme.text.secondary,
    },
    cardDetails: {
        marginTop: spacing.l,
        paddingTop: spacing.l,
        borderTopWidth: 1,
        borderTopColor: theme.border.subtle,
    },
    detailGrid: {
        gap: spacing.m,
    },
    detailRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: spacing.s,
    },
    detailLabel: {
        width: 60,
    },
    viewDetailsButton: {
        marginTop: spacing.l,
    },
    statusBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 10,
        paddingVertical: 5,
        borderRadius: radius.full,
        gap: 5,
        borderWidth: 1,
    },
    statusDot: {
        width: 7,
        height: 7,
        borderRadius: 3.5,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.5,
        shadowRadius: 3,
    },
    statusText: {
        fontWeight: '700',
        fontSize: 11,
        letterSpacing: 0.3,
    },
    emptyState: {
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: spacing.xxl * 1.5,
        paddingHorizontal: spacing.xxl,
    },
    emptyTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: theme.text.primary,
        marginTop: spacing.l,
        letterSpacing: 0.2,
    },
    emptySubtitle: {
        fontSize: 15,
        color: theme.text.secondary,
        textAlign: 'center',
        marginTop: spacing.s,
        lineHeight: 22,
    },
    datePickerButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: theme.background.subtle,
        paddingHorizontal: spacing.l,
        borderRadius: radius.m,
        borderWidth: 1,
        borderColor: theme.border.subtle,
        height: 54,
    },
    datePickerContent: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: spacing.s,
    },
    chip: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: spacing.m,
        paddingVertical: spacing.s,
        borderRadius: radius.full,
        borderWidth: 1,
        marginRight: spacing.xs,
        marginBottom: spacing.xs,
    },
    chipsContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: spacing.s,
        marginTop: spacing.xs,
        marginBottom: spacing.m,
    },
    sectionLabel: {
        fontSize: 12,
        fontWeight: '700',
        textTransform: 'uppercase',
        letterSpacing: 1,
        color: theme.text.tertiary,
        marginBottom: spacing.xs,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.6)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: spacing.xl,
    },
    modalContent: {
        width: '100%',
        maxWidth: 400,
        backgroundColor: theme.background.default,
        borderRadius: radius.xxl,
        padding: spacing.xl,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 12 },
        shadowOpacity: 0.3,
        shadowRadius: 24,
        elevation: 12,
        borderWidth: 1,
        borderColor: theme.mode === 'dark' ? theme.border.subtle : 'transparent',
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: spacing.l,
    },
    modalTitle: {
        fontSize: 19,
        fontWeight: '800',
        color: theme.text.primary,
        letterSpacing: 0.3,
    },
    resultsHeaderLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: spacing.s,
    },
    sortSection: {
        position: 'relative',
        zIndex: 100,
    },
    sortLabel: {
        fontSize: 11,
        fontWeight: '700',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
        color: theme.text.tertiary,
        marginRight: spacing.xs,
    },
    dropdownSelector: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: spacing.xs,
        backgroundColor: theme.mode === 'dark' ? '#1e293b' : '#f1f5f9', // Fully solid selector background
        paddingHorizontal: spacing.m,
        paddingVertical: 6,
        borderRadius: radius.m,
    },
    dropdownSelectorText: {
        fontSize: 13,
        fontWeight: '700',
        color: theme.palette.primary[500],
    },
    dropdownContainer: {
        position: 'absolute',
        top: 36,
        right: 0,
        width: 170,
        backgroundColor: theme.mode === 'dark' ? '#0f172a' : '#ffffff', // High contrast solid background
        borderRadius: radius.m,
        borderWidth: 1,
        borderColor: theme.mode === 'dark' ? 'rgba(255, 255, 255, 0.12)' : 'rgba(0, 0, 0, 0.08)', // Thin boundary line
        overflow: 'hidden',
        zIndex: 200,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.35, // High contrast shadow
        shadowRadius: 12,
        elevation: 10,
    },
    dropdownItem: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: spacing.m,
        paddingVertical: 10,
    },
    dropdownItemActive: {
        backgroundColor: theme.mode === 'dark' ? 'rgba(59, 130, 246, 0.25)' : 'rgba(59, 130, 246, 0.1)', // More prominent active item background
    },
    dropdownItemText: {
        fontSize: 13,
        color: theme.text.secondary,
        fontWeight: '500',
    },
    dropdownItemTextActive: {
        color: theme.palette.primary[500],
        fontWeight: '700',
    },
    footerLoader: {
        paddingVertical: spacing.l,
        alignItems: 'center',
    },
    listHeader: {
        zIndex: 99,
        elevation: 99,
        position: 'relative',
    }
});
