import { StyleSheet, ViewStyle, TextStyle, Dimensions } from 'react-native';
import { ColorTheme } from '../../theme/colors';
import { spacing } from '../../theme/spacing';
import { radius } from '../../theme/radius';

const { width } = Dimensions.get('window');

export const createStyles = (theme: ColorTheme, insets: any) => StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: theme.background.default,
    },
    scrollContent: {
        paddingTop: insets.top + 50,
        paddingHorizontal: spacing.l,
        paddingBottom: 120,
        alignItems: 'center',
    },

    floatingBackButton: {
        position: 'absolute',
        top: insets.top + 8,
        left: spacing.l - 10,
        width: 44,
        height: 44,
        borderRadius: 22,
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 10,
        backgroundColor: theme.mode === 'dark' ? 'rgba(255, 255, 255, 0.05)' : 'rgba(0, 0, 0, 0.03)',
    } as ViewStyle,

    // Hero Section
    heroTitle: {
        fontSize: 26,
        fontWeight: '700',
        color: theme.text.primary,
        textAlign: 'center',
        letterSpacing: -0.4,
        lineHeight: 32,
        marginBottom: 6,
    } as TextStyle,
    heroSubtitle: {
        fontSize: 14,
        color: theme.text.secondary,
        textAlign: 'center',
        marginBottom: 24,
        paddingHorizontal: 16,
        lineHeight: 20,
    } as TextStyle,

    // Digital ID Geometry
    cardWrapper: {
        width: width - spacing.l * 2,
        aspectRatio: 0.63,
        borderRadius: 20,
        overflow: 'hidden',
        backgroundColor: theme.background.card,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: theme.mode === 'dark' ? 0.4 : 0.08,
        shadowRadius: 16,
        elevation: 8,
        marginBottom: 40,
        borderWidth: 1,
        borderColor: theme.border.subtle,
    } as ViewStyle,
    cardMainGradient: {
        ...StyleSheet.absoluteFillObject,
        opacity: 0.03,
    },
    cardPattern: {
        position: 'absolute',
        top: -60,
        right: -60,
        width: 200,
        height: 200,
        borderRadius: 100,
        backgroundColor: theme.palette.primary[500],
        opacity: 0.05,
    },
    cardContent: {
        flex: 1,
        padding: 30,
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    cardLogo: {
        width: 50,
        height: 50,
        borderRadius: 14,
        backgroundColor: theme.mode === 'dark' ? 'rgba(255, 255, 255, 0.03)' : 'rgba(0, 0, 0, 0.02)',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: theme.border.subtle,
    },
    qrContainer: {
        width: 160,
        height: 160,
        borderRadius: 16,
        backgroundColor: '#FFF',
        padding: 16,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 10,
        elevation: 4,
    },
    qrPlaceholder: {
        width: '100%',
        height: '100%',
        justifyContent: 'center',
        alignItems: 'center',
    },
    doctorInfo: {
        alignItems: 'center',
    },
    doctorBadge: {
        paddingHorizontal: 10,
        paddingVertical: 5,
        borderRadius: 6,
        backgroundColor: theme.palette.primary[500] + '15',
        marginBottom: 10,
        borderWidth: 1,
        borderColor: theme.palette.primary[500] + '20',
    },
    doctorBadgeText: {
        fontSize: 10,
        fontWeight: '700',
        color: theme.palette.primary[500],
        textTransform: 'uppercase',
        letterSpacing: 0.8,
    },
    doctorName: {
        fontSize: 24,
        fontWeight: '700',
        color: theme.text.primary,
        textAlign: 'center',
        letterSpacing: -0.3,
    } as TextStyle,
    doctorSpecialty: {
        fontSize: 13,
        color: theme.text.tertiary,
        fontWeight: '600',
        textTransform: 'uppercase',
        letterSpacing: 1.5,
        marginTop: 4,
    } as TextStyle,

    // Floating Action Capsule
    actionCapsule: {
        position: 'absolute',
        bottom: 30,
        left: spacing.l,
        right: spacing.l,
        height: 64,
        borderRadius: 20,
        backgroundColor: theme.background.card,
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 8,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.1,
        shadowRadius: 12,
        elevation: 8,
        borderWidth: 1,
        borderColor: theme.border.subtle,
    } as ViewStyle,
    mainAction: {
        flex: 2,
        height: 48,
        borderRadius: 12,
        overflow: 'hidden',
    },
    mainActionGradient: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 6,
    },
    mainActionText: {
        fontSize: 14,
        fontWeight: '700',
        color: '#FFF',
    },
    iconAction: {
        width: 48,
        height: 48,
        borderRadius: 12,
        backgroundColor: theme.mode === 'dark' ? 'rgba(255, 255, 255, 0.04)' : 'rgba(0, 0, 0, 0.02)',
        justifyContent: 'center',
        alignItems: 'center',
        marginLeft: 8,
    },

    // Benefit Pods
    perksGrid: {
        width: '100%',
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 12,
        marginTop: 10,
    },
    perkPod: {
        flex: 1,
        minWidth: '45%',
        padding: 18,
        borderRadius: 16,
        backgroundColor: theme.background.card,
        borderWidth: 1,
        borderColor: theme.border.subtle,
    },
    perkTitle: {
        fontSize: 13,
        fontWeight: '700',
        color: theme.text.primary,
        marginTop: 10,
        marginBottom: 2,
    },
    perkDesc: {
        fontSize: 12,
        color: theme.text.secondary,
        lineHeight: 16,
    },
});
